language: generic

os:
 - osx

sudo: false

env:
  global:
    secure: "gUnBiclSuzSUSyJCVM2acIjry1VoqDlqWCkIDYx4VHJfRn7VXrav+G0cn2nYW7L8ch3/tnLqXLNEYRoBq8tbNOoOnnksqd0zTDNuUD4HkaQ47fNTsSbBVDzgDSiTvj9hjUFM7hQ0ju1BffG/uu43gl1mOaSh+R5/jdJ+iGlF+gg="

before_install:
  - brew remove --ignore-dependencies --force $(brew list)

install:
  - URL="https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh"
  - curl -L $URL -o miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda update --yes conda

  # Configure channels.
  - conda config --set show_channel_urls True
  - conda config --add channels scitools

  - conda install --yes -c conda-forge conda-build-all
  # https://github.com/SciTools/conda-build-all/issues/79
  - conda install --yes conda==4.2.16
  - conda list

script:
  - if [[ "$BINSTAR_TOKEN" == "" ]]; then
      export UPLOAD="";
    else
      export UPLOAD="--upload-channels scitools";
    fi
  - conda-build-all ./ $UPLOAD --inspect-channels scitools/label/main --matrix-condition "numpy >=1.8,,<=1.10" "python >=2.7,<3|>=3.4,<3.5|>=3.5,<3.6"
