package:
  name: cartopy
  version: !!str 0.11.1
source:
  git_url: https://github.com/SciTools/cartopy.git
  git_tag: v0.11.1

requirements:
  build:
    - python
    - six
    - numpy
    - cython
    - proj4
    - geos
    - shapely ==1.4.1
    - owslib # (only needed for test dependency)
  run:
    - python
    - six
    - mock
    - nose
    - pil
    - owslib
    - numpy
    - proj4
    - shapely
    - scipy
    - pyshp
    - matplotlib

test:
  imports:
    - cartopy
    - cartopy.mpl.geoaxes

about:
  home: http://scitools.org.uk/cartopy
  license: GNU LGPL
  summary: 'A library providing cartographic tools for python'

