package:
    name: udunits
    version: 2.2.16

source:
    fn: udunits-2.2.16.tar.gz
    url: ftp://ftp.unidata.ucar.edu/pub/udunits/udunits-2.2.16.tar.gz

build:
    number: 0

test:
    commands:
        - udunits2 -h

about:
  home: http://www.unidata.ucar.edu/software/udunits/
  summary: The UDUNITS package supports units of physical quantities.
