package:
    name: udunits
    version: 2.2.16

source:
    fn: v2.2.16.tar.gz
    url: https://github.com/Unidata/UDUNITS-2/archive/v2.2.16.tar.gz
    sha1: ee5d50a4505a24c5eb9192b3e3c7595c1a50572a

build:
    number: 0

test:
    commands:
        - udunits2 -h

about:
  home: http://www.unidata.ucar.edu/software/udunits/
  summary: The UDUNITS package supports units of physical quantities.
